AssistMe/Controllers/DocumentController.cs
using AssistMe.Data;
using AssistMe.Helpers;
using Google.Apis.Drive.v2;
using log4net;
using System;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace AssistMe.Controllers
{
    [CustomAuthorize]
    public class DocumentController : Controller
    {
        private static readonly ILog log = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        private UserConfig userConfig
        {
            get
            {
                return (UserConfig)Session["UserConfig"];
            }
        }

        public ActionResult FolderTag()
        {
            var folders = userConfig.DB.AssistMeDrive.Children
                .Where(f => f.IsFolder)
                .Select(f => f.DisplayName).ToArray();

            var result = Json(folders, JsonRequestBehavior.AllowGet);
            return result;
        }

        public ActionResult ListGDrive()
        {
            var service = HttpContext.Session["DriveService"] as DriveService;
            var gHelper = new GDriveHelper();
            var list = gHelper.GetAllFiles(service);
            var model = list.Items.Select(f => f.GetGFile<AFileInfo>());
            return PartialView("_ListGDrive", model);
        }

        //
        // GET: /Document/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Document/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            var userConfig = (UserConfig)Session["UserConfig"];

            try
            {
                var fileInfo = new AFileInfo
                {
                    Id = collection["Id"],
                    Description = collection["Description"],
                    DetailedInfo = collection["DetailedInfo"],
                    DisplayName = collection["DisplayName"],
                    FolderName = collection["FolderName"],
                };

                var folder = new AFolderInfo
                {
                    ParentId = userConfig.DB.AssistMeDrive.Id,
                    FileName = fileInfo.FolderName,
                    DisplayName = fileInfo.FolderName,
                };
                var service = HttpContext.Session["DriveService"] as DriveService;
                var ghelper = new GDriveHelper();
                var serverFolder = ghelper.GetDriveFileMetadata(folder, service, CreateIfNotExist: true);

                folder.Id = serverFolder.Id;

                //check folder already exist
                var existingFolder = userConfig.DB.AssistMeDrive.GetChild(folder.Id);
                if (existingFolder == null)
                {
                    var parentofFolder = userConfig.DB.AssistMeDrive.GetChild(folder.ParentId);
                    parentofFolder.Children.Add(folder);
                }
                //TODO: If folder changed while editing, Remove the file from older folder
                fileInfo.ParentId = folder.Id;

                Google.Apis.Drive.v2.Data.File driveFile = null;
                if (Request.Files.Count > 0 && Request.Files[0].ContentLength > 0)
                {
                    var file = Request.Files[0];
                    fileInfo.FileName = file.FileName;
                    driveFile = ghelper.CreateFile(fileInfo, service, file.InputStream);
                }
                else
                {
                    driveFile = ghelper.GetDriveFileMetadata(fileInfo, service);
                }

                fileInfo.Id = driveFile.Id;
                fileInfo.DownloadUrl = driveFile.DownloadUrl;
                fileInfo.ThumbnailUrl = driveFile.ThumbnailLink;

                var existingFile = userConfig.DB.AssistMeDrive.GetChild(fileInfo.Id);
                if (existingFile != null && existingFile.ParentId != null)
                {
                    var folderOfFile = userConfig.DB.AssistMeDrive.GetChild(existingFile.ParentId);
                    folderOfFile.Children.Remove(folderOfFile.Children.First(f => f.Id == existingFile.Id));
                }

                var parentFolderInDb = userConfig.DB.AssistMeDrive.GetChild(fileInfo.ParentId);
                parentFolderInDb.Children.Add(fileInfo);

                var dbFile = userConfig.DB.AssistMeDrive.Children.First(f => f.FileName != null && f.FileName == userConfig.DB_NAME);
                if (string.IsNullOrWhiteSpace(dbFile.Id))
                {
                    var serverDbFile = ghelper.GetDriveFileMetadata(new AFileInfo
                    {
                        ParentId = userConfig.DB.AssistMeDrive.Id,
                        FileName = userConfig.DB_NAME,
                    }, service);
                    dbFile.Id = serverDbFile.Id;
                    dbFile.IsSystemFile = true;
                }

                ghelper.WriteDBDataToLocalDB();

                if (log.IsDebugEnabled)
                    log.DebugFormat("Document add/update completed without error. User:{0}", userConfig.User_Id);

                return RedirectToAction("Index", "Home");
            }
            catch (Exception exp)
            {
                log.Error(string.Format("User:{0}, Message:{1}", userConfig.User_Id, exp.Message), exp);
                return RedirectToAction("Index", "Home");
            }
        }

        //
        // GET: /Document/Edit/5

        public ActionResult Edit(string id)
        {
            var aFile = userConfig.DB.AssistMeDrive.GetChild(id);
            return View(string.Format("Create", id), aFile);
        }

        //
        // POST: /Document/Edit/5

        public ActionResult Download(string id)
        {
            var userConfig = (UserConfig)Session["UserConfig"];
            var aFile = userConfig.DB.AssistMeDrive.GetChild(id);

            return File(DownloadFile(aFile.DownloadUrl),
                System.Net.Mime.MediaTypeNames.Application.Octet, aFile.FileName);
        }

        public static System.IO.Stream DownloadFile(string DownloadUrl)
        {
            if (!String.IsNullOrEmpty(DownloadUrl))
            {
                try
                {
                    var userConfig = (UserConfig)System.Web.HttpContext.Current.Session["UserConfig"];

                    HttpWebRequest request = (HttpWebRequest)WebRequest.Create(
                        new Uri(DownloadUrl));

                    request.Headers.Add("Authorization", "Bearer " + userConfig.GoogleAccessToken);
                    HttpWebResponse response = (HttpWebResponse)request.GetResponse();
                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        return response.GetResponseStream();
                    }
                    else
                    {
                        Console.WriteLine(
                            "An error occurred: " + response.StatusDescription);
                        return null;
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine("An error occurred: " + e.Message);
                    return null;
                }
            }
            else
            {
                // The file doesn't have any content stored on Drive.
                return null;
            }
        }
    }
}

AssistMe/Views/Document/Create.cshtml
@model AssistMe.Data.AFileInfo

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-lg-6">
        @using (Html.BeginForm("Create", "Document", FormMethod.Post, new { enctype = "multipart/form-data", id = "DocAdd" }))
        {
            @Html.AntiForgeryToken()

            <fieldset>
                @if (Model != null)
                { 
                    <legend>Edit document</legend>
                }
                else
                { 
                    <legend>Add/Create document</legend>
                    <div class="editor-label">
                        <label>File selection</label>
                    </div>
                    <div class="editor-field">
                        <input type="button" data-toggle="modal" data-target="#driveModal" value="Select from Google Drive" />
                        or
                    <input type="file" name="fileupload" id="fileupload" />
                    </div>
                }

                @Html.HiddenFor(m => m.Id)

                <div class="editor-field">
                    @Html.TextBoxFor(model => model.FolderName, null, new { @class = "typeahead", placeholder = "Folder name, Required" })<br />
                    @Html.ValidationMessageFor(model => model.FolderName)
                </div>

                <div class="editor-field">
                    @Html.TextBoxFor(model => model.DisplayName, null, new { @placeholder = "Display text, Required" })<br />
                    @Html.ValidationMessageFor(model => model.DisplayName)
                </div>

                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Description, null, new { @placeholder = "Description" })
                </div>

                <div class="editor-field">
                    @Html.TextBoxFor(model => model.DetailedInfo, null, new { @placeholder = "Additional info" })
                </div>

                <p>
                    <input type="submit" value="@(Model != null ? "Update" : "Add")" />
                </p>
            </fieldset>
        }
    </div>
    <div class="col-lg-6">
        <legend>
            @if (Model != null)
            {
                @Html.Raw("Preview");
            }
        </legend>
        @if (Model != null)
        {
            <img alt="No image" src="https://drive.google.com/thumbnail?id=@Model.Id" width="auto" height="auto" />
            <a id="downloadlink" href="@Url.Action("Download", "Document", new { id = Model.Id })" target="_blank">download</a>
        }
    </div>
</div>
@Html.ActionLink("Back", "Index", "Home")

<div class="modal fade" id="driveModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" data-dismiss="modal">×</button>
                <h4>Files on google drive</h4>
            </div>
            <div class="modal-body">
                <div id="gfiles" style="height: auto; max-height: 300px; overflow: auto;">
                    <div id="contents">Loading...</div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#DocAdd').submit(function () {
        var fileId = $('#Id').val();
        var file = $('#fileupload').val();
        if ((fileId != null && fileId.trim().length > 1) || (file != null && file.trim().length > 1))
            return true;
        else {
            alert('No file selected');
            return false;
        }
    });
    $(document).ready(function () {
        $.ajax({
            url: "@Url.Action("FolderTag")",
            type: "GET",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            error: function (response) {
                alert(response.responseText);
            },
            success: function (response) {
                // constructs the suggestion engine
                var folders = new Bloodhound({
                    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
                    queryTokenizer: Bloodhound.tokenizers.whitespace,
                    local: $.map(response, function (folder) { return { value: folder }; })
                });
                // kicks off the loading/processing of `local` and `prefetch`
                folders.initialize();

                $('.typeahead').typeahead({
                    hint: true,
                    highlight: true,
                    minLength: 1
                },
                {
                    name: 'folders',
                    displayKey: 'value',
                    // `ttAdapter` wraps the suggestion engine in an adapter that
                    // is compatible with the typeahead jQuery plugin
                    source: folders.ttAdapter()
                });
            }
        });
    });

    $('#driveModal').on('show.bs.modal', function (data) {
        $.get("@Url.Action("ListGDrive")", function (response) {
            $('#gfiles').empty().append(response);
        });
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AssistMe/Views/Document/_ListGDrive.cshtml
@model IEnumerable<AssistMe.Data.AFileInfo>
<ul>
    @foreach (var item in Model)
    {
        <li><a class="gfile" id="@item.Id">@item.DisplayName</a></li>
    }
</ul>
<script type="text/javascript">
    $('.gfile').click(function (data) {
        $('#Id').val(this.id);
        $('#driveModal').modal('hide');
    });
</script>